version: '3'

services:
  app:
    build:
      context: .
      dockerfile: user-service.dockerfile
    container_name: user-service
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_DATABASE=users
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_USERNAME=admin
      - SPRING_DATA_MONGODB_PASSWORD=admin
      - SPRING_DATA_MONGODB_AUTHENTICATION-DATABASE=admin
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - userservice

  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_DATABASE=users
      - MONGO_INITDB_ROOT_PASSWORD=admin
    networks:
      - userservice

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_MONGODB_SERVER=mongo_db
      - ME_CONFIG_BASICAUTH_USERNAME=test
      - ME_CONFIG_BASICAUTH_PASSWORD=test
    networks:
      - userservice

volumes:
  mongo: {}

networks:
  userservice:
