spring:
  data:
    mongodb:
      auto-index-creation: true
      username: admin
      password: admin
      host: localhost
      port: 27017
      database: users
      authentication-database: admin

secret: "sagwg][alwglwa]g2224"

server:
  servlet:
    context-path: /api/v1
  port: 8080